name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Setup lint tools
        run: |
          go get github.com/fzipp/gocyclo/cmd/gocyclo
          go get github.com/uudashr/gocognit/cmd/gocognit
          go get honnef.co/go/tools/cmd/staticcheck
      - name: Staticcheck
        run: staticcheck -fail ./...
      - name: Cyclometric Complexity
        run: gocyclo -over 15 .
      - name: Cognitive Complexity
        run: gocognit -over 15 .

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Build
      run: make build
    - name: Test
      run: make test
